version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: jdih_db
      POSTGRES_USER: jdih_user
      POSTGRES_PASSWORD: jdih_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  qdrant_data:
  postgres_data:
